#!/usr/bin/env bash
# This script prints "Best School" 10 times and says "Hi" after the 9th time
while [ "$count" -le 10 ]
do
    echo "Best School"
    if [ "$count" -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
